### ISSUE TITLE
possible to specify host-ip?

### ISSUE THREAD

**Issue by strowi** [groupon/Selenium-Grid-Extras#201]
Hi,

i am experimenting with docker-containers... I currently have multiple containers running on a single host with a hub. Running a test seems to work fine an gives me a video-link on the hub-webpage.
Problem is, this link points to the internal ip of the container that is not reachable from the outside.
Is there a way to specify the ip manually?

**Comment by dimacus** [comment]
Have you tried to expose ports? Expose 3000 and you should be able to see it.

Other option is to mount a host folder as a drive in container and save videos to that.

Do you mind sharing code for docker compose? I'd love to post it for everyone to use

Sent via Payphone

**Comment by strowi** [comment]
Yes, and it is not a problem with exposing ports.
Now on the next day i am not entirely sure this can be fixed.. (it's really hard to get a grasp on it with the current state of documentation, esp. cmdline-args like specifying ip/port..) but anyways..

The setup currently looks like this:
On the remote host a haproxy is dynamically (consul/registrator-setup) forwarding to the (private) container-ip/port:

```
...
haproxy:
  image: my.own.registry/haproxy:latest
  cpu_shares: 10
  mem_limit: 256m
  restart: always

  ports:
    - "80:80"
    - "443:443"
    - "1936:1936"
    - "3000:3000"
    - "3001:3001"
    - "3002:3002"
    - "3003:3003"

  links:
    - consul:consul

  volumes:
    - /srv/haproxy:/usr/local/etc/haproxy/

# Selenium-Grid
selhub:
  image: my.own.registry/selhub:latest

  ports:
    - 4444:4444

selnodeff:
  image: my.own.registry/selnodeff:latest
  ports:
    - 5901:5900
  links:
    - selhub:hub

selnodeff-esr:
  image: my.own.registry/selnodeff-esr:latest
  ports:
    - 5902:5900
  links:
    - selhub:hub

selnodechrome:
  image: my.own.registry/selnodechrome:latest
  ports:
    - 5903:5900
  links:
    - selhub:hub
```

Now... most parts work as expected, i can browse the hub/console and every other container by the hosts IP and the port exported by haproxy ( haproy forwards 3001 -> selnodeff:3000 etc..).
Running a test also works ( i checked via vnc).
But the video-link that appears on the hub or on the containers-website contains the private ip of the container (172.x.x.x) which of course is unreachable from a remote.
